// <auto-generated />
using System;
using System.Collections.Generic;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(TelemetryContext))]
    [Migration("20251103181912_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Telemetry")
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Clinic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Clinics", "Telemetry");

                    b.HasData(
                        new
                        {
                            Id = new Guid("14444444-4444-4444-4444-444444444444"),
                            Address = "123 Main Street",
                            City = "New York"
                        },
                        new
                        {
                            Id = new Guid("24444444-4444-4444-4444-444444444444"),
                            Address = "456 Oak Avenue",
                            City = "Los Angeles"
                        },
                        new
                        {
                            Id = new Guid("34444444-4444-4444-4444-444444444444"),
                            Address = "789 Pine Street",
                            City = "Chicago"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Address = "321 Elm Street",
                            City = "Houston"
                        },
                        new
                        {
                            Id = new Guid("54444444-4444-4444-4444-444444444444"),
                            Address = "654 Beach Boulevard",
                            City = "Miami"
                        });
                });

            modelBuilder.Entity("DoctorPatient", b =>
                {
                    b.Property<Guid>("PatientsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("doctorsId")
                        .HasColumnType("uuid");

                    b.HasKey("PatientsId", "doctorsId");

                    b.HasIndex("doctorsId");

                    b.ToTable("DoctorPatient", "Telemetry");
                });

            modelBuilder.Entity("Domain.Entities.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Appointments", "Telemetry");
                });

            modelBuilder.Entity("Domain.Entities.Doctor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<Guid>("ClinicId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DoctorInfoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId");

                    b.HasIndex("DoctorInfoId")
                        .IsUnique();

                    b.ToTable("Doctors", "Telemetry");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3be5f0b8-ca6a-4273-80a5-3524051a336f"),
                            Capacity = 22,
                            ClinicId = new Guid("34444444-4444-4444-4444-444444444444"),
                            Specialty = "Oncology"
                        },
                        new
                        {
                            Id = new Guid("55cd9f5a-3d91-4e6a-879a-a1a82e3ed957"),
                            Capacity = 25,
                            ClinicId = new Guid("24444444-4444-4444-4444-444444444444"),
                            Specialty = "Oncology"
                        },
                        new
                        {
                            Id = new Guid("f8f35928-3eec-4a5e-b0b7-abef7bdde488"),
                            Capacity = 16,
                            ClinicId = new Guid("24444444-4444-4444-4444-444444444444"),
                            Specialty = "Oncology"
                        },
                        new
                        {
                            Id = new Guid("0fd4ac44-475a-40a6-be28-2428dc34dad2"),
                            Capacity = 39,
                            ClinicId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Specialty = "Neurology"
                        },
                        new
                        {
                            Id = new Guid("121fa33d-5346-4be0-96c3-17f9a2a8dba4"),
                            Capacity = 26,
                            ClinicId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Specialty = "Cardiology"
                        },
                        new
                        {
                            Id = new Guid("659b8ae3-84d1-4c2c-93eb-bfd2779953e3"),
                            Capacity = 31,
                            ClinicId = new Guid("24444444-4444-4444-4444-444444444444"),
                            Specialty = "Ophthalmology"
                        },
                        new
                        {
                            Id = new Guid("273f2b49-1139-49b9-961b-f9c7e1a1c42e"),
                            Capacity = 13,
                            ClinicId = new Guid("34444444-4444-4444-4444-444444444444"),
                            Specialty = "Psychiatry"
                        },
                        new
                        {
                            Id = new Guid("f859601d-63a9-4521-9164-cabcefcfcd73"),
                            Capacity = 12,
                            ClinicId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Specialty = "Surgery"
                        },
                        new
                        {
                            Id = new Guid("89448b26-e257-48a9-a7c5-a38b489a2675"),
                            Capacity = 26,
                            ClinicId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Specialty = "Cardiology"
                        },
                        new
                        {
                            Id = new Guid("94f06519-ddea-4a8f-830f-5236f164e8a1"),
                            Capacity = 10,
                            ClinicId = new Guid("24444444-4444-4444-4444-444444444444"),
                            Specialty = "Cardiology"
                        },
                        new
                        {
                            Id = new Guid("a27723f7-67e6-4ac1-abcb-dc2ef98e4803"),
                            Capacity = 22,
                            ClinicId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Specialty = "Neurology"
                        },
                        new
                        {
                            Id = new Guid("36350ca8-7a67-4cbe-bf09-ecd7ae6a4fe1"),
                            Capacity = 18,
                            ClinicId = new Guid("34444444-4444-4444-4444-444444444444"),
                            Specialty = "Neurology"
                        },
                        new
                        {
                            Id = new Guid("7de3617e-6a01-46ba-a16e-e474d3cf9cc8"),
                            Capacity = 17,
                            ClinicId = new Guid("24444444-4444-4444-4444-444444444444"),
                            Specialty = "Ophthalmology"
                        },
                        new
                        {
                            Id = new Guid("7c30f1f2-98d5-4208-92ff-3cbb436b78ec"),
                            Capacity = 24,
                            ClinicId = new Guid("34444444-4444-4444-4444-444444444444"),
                            Specialty = "Surgery"
                        },
                        new
                        {
                            Id = new Guid("29de7f3a-a9c8-4c82-a70b-f096dcfc10f3"),
                            Capacity = 22,
                            ClinicId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Specialty = "Surgery"
                        },
                        new
                        {
                            Id = new Guid("176424da-7b51-42b7-83d8-a5bc27b50115"),
                            Capacity = 24,
                            ClinicId = new Guid("24444444-4444-4444-4444-444444444444"),
                            Specialty = "Neurology"
                        },
                        new
                        {
                            Id = new Guid("6def89c2-3fb8-4672-ad36-9c9d48db5f4b"),
                            Capacity = 15,
                            ClinicId = new Guid("34444444-4444-4444-4444-444444444444"),
                            Specialty = "Psychiatry"
                        },
                        new
                        {
                            Id = new Guid("d76151b9-8f33-4bf9-a996-028431b8867a"),
                            Capacity = 35,
                            ClinicId = new Guid("24444444-4444-4444-4444-444444444444"),
                            Specialty = "Pediatrics"
                        },
                        new
                        {
                            Id = new Guid("6b0d8f83-ae22-4210-89f4-b2a7749423fb"),
                            Capacity = 37,
                            ClinicId = new Guid("34444444-4444-4444-4444-444444444444"),
                            Specialty = "Ophthalmology"
                        },
                        new
                        {
                            Id = new Guid("b85b4049-c010-41d6-b3d3-f81994b72246"),
                            Capacity = 20,
                            ClinicId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Specialty = "Neurology"
                        });
                });

            modelBuilder.Entity("Domain.Entities.DomainEntities.CalendarBlock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BlockReason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsBusy")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId")
                        .IsUnique();

                    b.ToTable("CalendarBlocks", "Telemetry");
                });

            modelBuilder.Entity("Domain.Entities.DomainEntities.MedicalRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("MedicalRecords", "Telemetry");
                });

            modelBuilder.Entity("Domain.Entities.DomainEntities.WorkSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.ComplexProperty<Dictionary<string, object>>("Friday", "Domain.Entities.DomainEntities.WorkSchedule.Friday#WorkingHours", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<TimeOnly?>("EndDate")
                                .HasColumnType("time without time zone");

                            b1.Property<TimeOnly?>("StartDate")
                                .HasColumnType("time without time zone");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Monday", "Domain.Entities.DomainEntities.WorkSchedule.Monday#WorkingHours", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<TimeOnly?>("EndDate")
                                .HasColumnType("time without time zone");

                            b1.Property<TimeOnly?>("StartDate")
                                .HasColumnType("time without time zone");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Saturday", "Domain.Entities.DomainEntities.WorkSchedule.Saturday#WorkingHours", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<TimeOnly?>("EndDate")
                                .HasColumnType("time without time zone");

                            b1.Property<TimeOnly?>("StartDate")
                                .HasColumnType("time without time zone");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Sunday", "Domain.Entities.DomainEntities.WorkSchedule.Sunday#WorkingHours", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<TimeOnly?>("EndDate")
                                .HasColumnType("time without time zone");

                            b1.Property<TimeOnly?>("StartDate")
                                .HasColumnType("time without time zone");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Thursday", "Domain.Entities.DomainEntities.WorkSchedule.Thursday#WorkingHours", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<TimeOnly?>("EndDate")
                                .HasColumnType("time without time zone");

                            b1.Property<TimeOnly?>("StartDate")
                                .HasColumnType("time without time zone");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Tuesday", "Domain.Entities.DomainEntities.WorkSchedule.Tuesday#WorkingHours", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<TimeOnly?>("EndDate")
                                .HasColumnType("time without time zone");

                            b1.Property<TimeOnly?>("StartDate")
                                .HasColumnType("time without time zone");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Wednesday", "Domain.Entities.DomainEntities.WorkSchedule.Wednesday#WorkingHours", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<TimeOnly?>("EndDate")
                                .HasColumnType("time without time zone");

                            b1.Property<TimeOnly?>("StartDate")
                                .HasColumnType("time without time zone");
                        });

                    b.HasKey("Id");

                    b.ToTable("WorkSchedules", "Telemetry");
                });

            modelBuilder.Entity("Domain.Entities.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("MedicalRecordId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MedicalRecordId")
                        .IsUnique();

                    b.ToTable("Patients", "Telemetry");
                });

            modelBuilder.Entity("Domain.Entities.SupportEntities.DoctorInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Awards")
                        .HasColumnType("text");

                    b.Property<string>("Education")
                        .HasColumnType("text");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Publications")
                        .HasColumnType("text");

                    b.Property<string>("Qualifications")
                        .HasColumnType("text");

                    b.Property<string>("ShortBio")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DoctorInfos", "Telemetry");
                });

            modelBuilder.Entity("DoctorPatient", b =>
                {
                    b.HasOne("Domain.Entities.Patient", null)
                        .WithMany()
                        .HasForeignKey("PatientsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Doctor", null)
                        .WithMany()
                        .HasForeignKey("doctorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Appointment", b =>
                {
                    b.HasOne("Domain.Entities.Doctor", "doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Patient", "patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Domain.ValueObjects.Period", "EventPeriod", b1 =>
                        {
                            b1.Property<Guid>("AppointmentId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("EndDate")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTime>("StartDate")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("AppointmentId");

                            b1.ToTable("Appointments", "Telemetry");

                            b1.WithOwner()
                                .HasForeignKey("AppointmentId");
                        });

                    b.Navigation("EventPeriod")
                        .IsRequired();

                    b.Navigation("doctor");

                    b.Navigation("patient");
                });

            modelBuilder.Entity("Domain.Entities.Doctor", b =>
                {
                    b.HasOne("Clinic", "Clinic")
                        .WithMany()
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.SupportEntities.DoctorInfo", "DoctorInfo")
                        .WithOne()
                        .HasForeignKey("Domain.Entities.Doctor", "DoctorInfoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Clinic");

                    b.Navigation("DoctorInfo");
                });

            modelBuilder.Entity("Domain.Entities.DomainEntities.CalendarBlock", b =>
                {
                    b.HasOne("Domain.Entities.Doctor", "Doctor")
                        .WithOne()
                        .HasForeignKey("Domain.Entities.DomainEntities.CalendarBlock", "DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Domain.ValueObjects.Period", "period", b1 =>
                        {
                            b1.Property<Guid>("CalendarBlockId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("EndDate")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTime>("StartDate")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("CalendarBlockId");

                            b1.ToTable("CalendarBlocks", "Telemetry");

                            b1.WithOwner()
                                .HasForeignKey("CalendarBlockId");
                        });

                    b.Navigation("Doctor");

                    b.Navigation("period")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.DomainEntities.WorkSchedule", b =>
                {
                    b.HasOne("Domain.Entities.Doctor", "Doctor")
                        .WithOne()
                        .HasForeignKey("Domain.Entities.DomainEntities.WorkSchedule", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("Domain.Entities.Patient", b =>
                {
                    b.HasOne("Domain.Entities.DomainEntities.MedicalRecord", "MedicalRecord")
                        .WithOne()
                        .HasForeignKey("Domain.Entities.Patient", "MedicalRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MedicalRecord");
                });

            modelBuilder.Entity("Domain.Entities.Doctor", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("Domain.Entities.Patient", b =>
                {
                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
