// <auto-generated />
using System;
using System.Collections.Generic;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(TelemetryContext))]
    [Migration("20251102194612_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Telemetry")
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Clinic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Clinics", "Telemetry");

                    b.HasData(
                        new
                        {
                            Id = new Guid("14444444-4444-4444-4444-444444444444"),
                            Address = "123 Main Street",
                            City = "New York"
                        },
                        new
                        {
                            Id = new Guid("24444444-4444-4444-4444-444444444444"),
                            Address = "456 Oak Avenue",
                            City = "Los Angeles"
                        },
                        new
                        {
                            Id = new Guid("34444444-4444-4444-4444-444444444444"),
                            Address = "789 Pine Street",
                            City = "Chicago"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Address = "321 Elm Street",
                            City = "Houston"
                        },
                        new
                        {
                            Id = new Guid("54444444-4444-4444-4444-444444444444"),
                            Address = "654 Beach Boulevard",
                            City = "Miami"
                        });
                });

            modelBuilder.Entity("DoctorPatient", b =>
                {
                    b.Property<Guid>("PatientsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("doctorsId")
                        .HasColumnType("uuid");

                    b.HasKey("PatientsId", "doctorsId");

                    b.HasIndex("doctorsId");

                    b.ToTable("DoctorPatient", "Telemetry");
                });

            modelBuilder.Entity("Domain.Entities.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Appointments", "Telemetry");
                });

            modelBuilder.Entity("Domain.Entities.Doctor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<Guid>("ClinicId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DoctorInfoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId");

                    b.HasIndex("DoctorInfoId")
                        .IsUnique();

                    b.ToTable("Doctors", "Telemetry");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4ef99f3c-6f37-4b6d-b704-620cf6b460c4"),
                            Capacity = 29,
                            ClinicId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Specialty = "Dermatology"
                        },
                        new
                        {
                            Id = new Guid("d808433a-ee98-4bed-9c8c-e2bfb628aed1"),
                            Capacity = 12,
                            ClinicId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Specialty = "Dermatology"
                        },
                        new
                        {
                            Id = new Guid("c1286101-66b8-4717-a97e-232584623f62"),
                            Capacity = 35,
                            ClinicId = new Guid("34444444-4444-4444-4444-444444444444"),
                            Specialty = "Ophthalmology"
                        },
                        new
                        {
                            Id = new Guid("010ec82e-cbb0-4287-8ae7-b2b3d15ec3bd"),
                            Capacity = 12,
                            ClinicId = new Guid("24444444-4444-4444-4444-444444444444"),
                            Specialty = "Cardiology"
                        },
                        new
                        {
                            Id = new Guid("aeddd81c-688a-4481-816c-a6983475ba45"),
                            Capacity = 29,
                            ClinicId = new Guid("24444444-4444-4444-4444-444444444444"),
                            Specialty = "Cardiology"
                        },
                        new
                        {
                            Id = new Guid("591e08d0-7117-4154-819e-297d1b597462"),
                            Capacity = 32,
                            ClinicId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Specialty = "Dermatology"
                        },
                        new
                        {
                            Id = new Guid("509c7f59-e199-4325-bd4a-2990d3118deb"),
                            Capacity = 36,
                            ClinicId = new Guid("24444444-4444-4444-4444-444444444444"),
                            Specialty = "Ophthalmology"
                        },
                        new
                        {
                            Id = new Guid("a038faff-7234-4101-baa4-186025dc1972"),
                            Capacity = 39,
                            ClinicId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Specialty = "Oncology"
                        },
                        new
                        {
                            Id = new Guid("c064aed7-b71a-4af2-a092-05f2a7d1f717"),
                            Capacity = 17,
                            ClinicId = new Guid("34444444-4444-4444-4444-444444444444"),
                            Specialty = "Psychiatry"
                        },
                        new
                        {
                            Id = new Guid("279c8e2c-3b46-4034-8b97-e9d1b93d05bc"),
                            Capacity = 17,
                            ClinicId = new Guid("34444444-4444-4444-4444-444444444444"),
                            Specialty = "Cardiology"
                        },
                        new
                        {
                            Id = new Guid("0538e8aa-a1cc-44ea-a733-298c2a3178df"),
                            Capacity = 25,
                            ClinicId = new Guid("34444444-4444-4444-4444-444444444444"),
                            Specialty = "Ophthalmology"
                        },
                        new
                        {
                            Id = new Guid("21d99907-299a-4199-b683-8c27e7919d07"),
                            Capacity = 21,
                            ClinicId = new Guid("24444444-4444-4444-4444-444444444444"),
                            Specialty = "Ophthalmology"
                        },
                        new
                        {
                            Id = new Guid("e1b0282d-fb1d-4add-83fa-182663c2f02f"),
                            Capacity = 35,
                            ClinicId = new Guid("24444444-4444-4444-4444-444444444444"),
                            Specialty = "Surgery"
                        },
                        new
                        {
                            Id = new Guid("b6cc452d-5711-47fd-aee5-a5483df8d31f"),
                            Capacity = 9,
                            ClinicId = new Guid("34444444-4444-4444-4444-444444444444"),
                            Specialty = "Neurology"
                        },
                        new
                        {
                            Id = new Guid("30f99b5a-c21a-4d58-9d9a-fb458f63b68e"),
                            Capacity = 21,
                            ClinicId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Specialty = "Psychiatry"
                        },
                        new
                        {
                            Id = new Guid("ce367d1b-affe-4b98-a1a9-9fe93629dfe7"),
                            Capacity = 9,
                            ClinicId = new Guid("34444444-4444-4444-4444-444444444444"),
                            Specialty = "Cardiology"
                        },
                        new
                        {
                            Id = new Guid("1a223f5f-dfee-4471-992b-7edf285e2efa"),
                            Capacity = 24,
                            ClinicId = new Guid("34444444-4444-4444-4444-444444444444"),
                            Specialty = "Ophthalmology"
                        },
                        new
                        {
                            Id = new Guid("b3304078-16d7-416f-806f-5b6e7197e56e"),
                            Capacity = 26,
                            ClinicId = new Guid("24444444-4444-4444-4444-444444444444"),
                            Specialty = "Neurology"
                        },
                        new
                        {
                            Id = new Guid("428c03d6-1ded-4d62-a279-5d28591b5634"),
                            Capacity = 31,
                            ClinicId = new Guid("24444444-4444-4444-4444-444444444444"),
                            Specialty = "Orthopedics"
                        },
                        new
                        {
                            Id = new Guid("bcd069af-9a79-4f17-8240-7e8414c23616"),
                            Capacity = 33,
                            ClinicId = new Guid("34444444-4444-4444-4444-444444444444"),
                            Specialty = "Dermatology"
                        });
                });

            modelBuilder.Entity("Domain.Entities.DomainEntities.MedicalRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("MedicalRecords", "Telemetry");
                });

            modelBuilder.Entity("Domain.Entities.DomainEntities.WorkSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.ComplexProperty<Dictionary<string, object>>("Friday", "Domain.Entities.DomainEntities.WorkSchedule.Friday#WorkingHours", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<TimeOnly?>("EndDate")
                                .HasColumnType("time without time zone");

                            b1.Property<TimeOnly?>("StartDate")
                                .HasColumnType("time without time zone");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Monday", "Domain.Entities.DomainEntities.WorkSchedule.Monday#WorkingHours", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<TimeOnly?>("EndDate")
                                .HasColumnType("time without time zone");

                            b1.Property<TimeOnly?>("StartDate")
                                .HasColumnType("time without time zone");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Saturday", "Domain.Entities.DomainEntities.WorkSchedule.Saturday#WorkingHours", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<TimeOnly?>("EndDate")
                                .HasColumnType("time without time zone");

                            b1.Property<TimeOnly?>("StartDate")
                                .HasColumnType("time without time zone");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Sunday", "Domain.Entities.DomainEntities.WorkSchedule.Sunday#WorkingHours", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<TimeOnly?>("EndDate")
                                .HasColumnType("time without time zone");

                            b1.Property<TimeOnly?>("StartDate")
                                .HasColumnType("time without time zone");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Thursday", "Domain.Entities.DomainEntities.WorkSchedule.Thursday#WorkingHours", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<TimeOnly?>("EndDate")
                                .HasColumnType("time without time zone");

                            b1.Property<TimeOnly?>("StartDate")
                                .HasColumnType("time without time zone");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Tuesday", "Domain.Entities.DomainEntities.WorkSchedule.Tuesday#WorkingHours", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<TimeOnly?>("EndDate")
                                .HasColumnType("time without time zone");

                            b1.Property<TimeOnly?>("StartDate")
                                .HasColumnType("time without time zone");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Wednesday", "Domain.Entities.DomainEntities.WorkSchedule.Wednesday#WorkingHours", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<TimeOnly?>("EndDate")
                                .HasColumnType("time without time zone");

                            b1.Property<TimeOnly?>("StartDate")
                                .HasColumnType("time without time zone");
                        });

                    b.HasKey("Id");

                    b.ToTable("WorkSchedules", "Telemetry");
                });

            modelBuilder.Entity("Domain.Entities.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("MedicalRecordId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MedicalRecordId")
                        .IsUnique();

                    b.ToTable("Patients", "Telemetry");
                });

            modelBuilder.Entity("Domain.Entities.SupportEntities.DoctorInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Awards")
                        .HasColumnType("text");

                    b.Property<string>("Education")
                        .HasColumnType("text");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Publications")
                        .HasColumnType("text");

                    b.Property<string>("Qualifications")
                        .HasColumnType("text");

                    b.Property<string>("ShortBio")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DoctorInfos", "Telemetry");
                });

            modelBuilder.Entity("DoctorPatient", b =>
                {
                    b.HasOne("Domain.Entities.Patient", null)
                        .WithMany()
                        .HasForeignKey("PatientsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Doctor", null)
                        .WithMany()
                        .HasForeignKey("doctorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Appointment", b =>
                {
                    b.HasOne("Domain.Entities.Doctor", "doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Patient", "patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Domain.ValueObjects.Period", "EventPeriod", b1 =>
                        {
                            b1.Property<Guid>("AppointmentId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("EndDate")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTime>("StartDate")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("AppointmentId");

                            b1.ToTable("Appointments", "Telemetry");

                            b1.WithOwner()
                                .HasForeignKey("AppointmentId");
                        });

                    b.Navigation("EventPeriod")
                        .IsRequired();

                    b.Navigation("doctor");

                    b.Navigation("patient");
                });

            modelBuilder.Entity("Domain.Entities.Doctor", b =>
                {
                    b.HasOne("Clinic", "Clinic")
                        .WithMany()
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.SupportEntities.DoctorInfo", "DoctorInfo")
                        .WithOne()
                        .HasForeignKey("Domain.Entities.Doctor", "DoctorInfoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Clinic");

                    b.Navigation("DoctorInfo");
                });

            modelBuilder.Entity("Domain.Entities.DomainEntities.WorkSchedule", b =>
                {
                    b.HasOne("Domain.Entities.Doctor", "Doctor")
                        .WithOne()
                        .HasForeignKey("Domain.Entities.DomainEntities.WorkSchedule", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("Domain.Entities.Patient", b =>
                {
                    b.HasOne("Domain.Entities.DomainEntities.MedicalRecord", "MedicalRecord")
                        .WithOne()
                        .HasForeignKey("Domain.Entities.Patient", "MedicalRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MedicalRecord");
                });

            modelBuilder.Entity("Domain.Entities.Doctor", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("Domain.Entities.Patient", b =>
                {
                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
