// <auto-generated />
using System;
using System.Collections.Generic;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(TelemetryContext))]
    [Migration("20251226202234_onemore")]
    partial class onemore
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Telemetry")
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Clinic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Clinics", "Telemetry");

                    b.HasData(
                        new
                        {
                            Id = new Guid("14444444-4444-4444-4444-444444444444"),
                            Address = "123 Main Street",
                            City = "New York"
                        },
                        new
                        {
                            Id = new Guid("24444444-4444-4444-4444-444444444444"),
                            Address = "456 Oak Avenue",
                            City = "Los Angeles"
                        },
                        new
                        {
                            Id = new Guid("34444444-4444-4444-4444-444444444444"),
                            Address = "789 Pine Street",
                            City = "Chicago"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Address = "321 Elm Street",
                            City = "Houston"
                        },
                        new
                        {
                            Id = new Guid("54444444-4444-4444-4444-444444444444"),
                            Address = "654 Beach Boulevard",
                            City = "Miami"
                        });
                });

            modelBuilder.Entity("DoctorPatient", b =>
                {
                    b.Property<Guid>("PatientsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("doctorsId")
                        .HasColumnType("uuid");

                    b.HasKey("PatientsId", "doctorsId");

                    b.HasIndex("doctorsId");

                    b.ToTable("DoctorPatient", "Telemetry");
                });

            modelBuilder.Entity("Domain.Entities.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.ComplexProperty<Dictionary<string, object>>("EventPeriod", "Domain.Entities.Appointment.EventPeriod#Period", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTime>("EndDate")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTime>("StartDate")
                                .HasColumnType("timestamp with time zone");
                        });

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Appointments", "Telemetry");
                });

            modelBuilder.Entity("Domain.Entities.CalendarBlock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BlockReason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsBusy")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId")
                        .IsUnique();

                    b.ToTable("CalendarBlocks", "Telemetry");
                });

            modelBuilder.Entity("Domain.Entities.Doctor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<Guid>("ClinicId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DoctorInfoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId");

                    b.HasIndex("DoctorInfoId")
                        .IsUnique();

                    b.ToTable("Doctors", "Telemetry");

                    b.HasData(
                        new
                        {
                            Id = new Guid("31efc166-6952-4bdf-8b41-9e671d8e0172"),
                            Capacity = 29,
                            ClinicId = new Guid("34444444-4444-4444-4444-444444444444"),
                            Specialty = "Orthopedics"
                        },
                        new
                        {
                            Id = new Guid("2ca9e97a-9579-4e60-b16c-646fde1bcdca"),
                            Capacity = 19,
                            ClinicId = new Guid("24444444-4444-4444-4444-444444444444"),
                            Specialty = "Pediatrics"
                        },
                        new
                        {
                            Id = new Guid("d6d1083b-5584-413f-90ec-39fa45cdc0c0"),
                            Capacity = 39,
                            ClinicId = new Guid("34444444-4444-4444-4444-444444444444"),
                            Specialty = "Dermatology"
                        },
                        new
                        {
                            Id = new Guid("c986b63d-ac03-4ac8-9382-3c20a88728b6"),
                            Capacity = 33,
                            ClinicId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Specialty = "Dermatology"
                        },
                        new
                        {
                            Id = new Guid("f095151b-0ad7-4750-a289-0f209021bfe0"),
                            Capacity = 28,
                            ClinicId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Specialty = "Neurology"
                        },
                        new
                        {
                            Id = new Guid("160577c6-94f9-4f39-8ab1-18211e448484"),
                            Capacity = 30,
                            ClinicId = new Guid("24444444-4444-4444-4444-444444444444"),
                            Specialty = "Surgery"
                        },
                        new
                        {
                            Id = new Guid("3c08352b-35cd-4ec0-9f1f-589b574ef97a"),
                            Capacity = 7,
                            ClinicId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Specialty = "Psychiatry"
                        },
                        new
                        {
                            Id = new Guid("d4b7811c-a7ce-4e4b-8734-df0dd7ca3a0e"),
                            Capacity = 33,
                            ClinicId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Specialty = "Cardiology"
                        },
                        new
                        {
                            Id = new Guid("cf8ae6cc-ba76-4384-abb7-a94b52f155e7"),
                            Capacity = 27,
                            ClinicId = new Guid("34444444-4444-4444-4444-444444444444"),
                            Specialty = "Oncology"
                        },
                        new
                        {
                            Id = new Guid("249d42c7-e8c1-45a5-86c5-54e9a3fdbadc"),
                            Capacity = 5,
                            ClinicId = new Guid("34444444-4444-4444-4444-444444444444"),
                            Specialty = "Cardiology"
                        },
                        new
                        {
                            Id = new Guid("242d0a32-87ef-4f13-81b4-bee8c1a6ed32"),
                            Capacity = 23,
                            ClinicId = new Guid("24444444-4444-4444-4444-444444444444"),
                            Specialty = "Radiology"
                        },
                        new
                        {
                            Id = new Guid("71b77986-aa73-442a-a25f-a7c523b9465c"),
                            Capacity = 7,
                            ClinicId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Specialty = "Oncology"
                        },
                        new
                        {
                            Id = new Guid("5ad8ad11-bcd4-4fb7-8d1c-1ea7d3b93341"),
                            Capacity = 11,
                            ClinicId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Specialty = "Radiology"
                        },
                        new
                        {
                            Id = new Guid("cc6b4cf4-a13b-49fa-83f6-651cc4f8b1c4"),
                            Capacity = 17,
                            ClinicId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Specialty = "Psychiatry"
                        },
                        new
                        {
                            Id = new Guid("3857df71-cc3b-45d1-9531-29e178451f02"),
                            Capacity = 6,
                            ClinicId = new Guid("24444444-4444-4444-4444-444444444444"),
                            Specialty = "Cardiology"
                        },
                        new
                        {
                            Id = new Guid("141694e8-0303-4bbf-a8d5-97a8122d69ad"),
                            Capacity = 19,
                            ClinicId = new Guid("24444444-4444-4444-4444-444444444444"),
                            Specialty = "Cardiology"
                        },
                        new
                        {
                            Id = new Guid("9382e511-8508-453b-b561-10be2b9f580f"),
                            Capacity = 13,
                            ClinicId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Specialty = "Dermatology"
                        },
                        new
                        {
                            Id = new Guid("dd40d06c-a281-49ca-bc4d-88041a737ca0"),
                            Capacity = 37,
                            ClinicId = new Guid("24444444-4444-4444-4444-444444444444"),
                            Specialty = "Ophthalmology"
                        },
                        new
                        {
                            Id = new Guid("fe29003c-efee-4504-aa95-682d63e4051b"),
                            Capacity = 17,
                            ClinicId = new Guid("24444444-4444-4444-4444-444444444444"),
                            Specialty = "Radiology"
                        },
                        new
                        {
                            Id = new Guid("eee5db30-095e-4d08-9b2f-79e359c591c4"),
                            Capacity = 31,
                            ClinicId = new Guid("24444444-4444-4444-4444-444444444444"),
                            Specialty = "Neurology"
                        });
                });

            modelBuilder.Entity("Domain.Entities.DoctorInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Awards")
                        .HasColumnType("text");

                    b.Property<string>("Education")
                        .HasColumnType("text");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Publications")
                        .HasColumnType("text");

                    b.Property<string>("Qualifications")
                        .HasColumnType("text");

                    b.Property<string>("ShortBio")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DoctorInfos", "Telemetry");
                });

            modelBuilder.Entity("Domain.Entities.MedicalRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("MedicalRecords", "Telemetry");
                });

            modelBuilder.Entity("Domain.Entities.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("MedicalRecordId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MedicalRecordId")
                        .IsUnique();

                    b.ToTable("Patients", "Telemetry");
                });

            modelBuilder.Entity("Domain.Entities.WorkSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.ComplexProperty<Dictionary<string, object>>("Friday", "Domain.Entities.WorkSchedule.Friday#WorkingHours", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<TimeOnly?>("EndDate")
                                .HasColumnType("time without time zone");

                            b1.Property<TimeOnly?>("StartDate")
                                .HasColumnType("time without time zone");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Monday", "Domain.Entities.WorkSchedule.Monday#WorkingHours", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<TimeOnly?>("EndDate")
                                .HasColumnType("time without time zone");

                            b1.Property<TimeOnly?>("StartDate")
                                .HasColumnType("time without time zone");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Saturday", "Domain.Entities.WorkSchedule.Saturday#WorkingHours", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<TimeOnly?>("EndDate")
                                .HasColumnType("time without time zone");

                            b1.Property<TimeOnly?>("StartDate")
                                .HasColumnType("time without time zone");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Sunday", "Domain.Entities.WorkSchedule.Sunday#WorkingHours", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<TimeOnly?>("EndDate")
                                .HasColumnType("time without time zone");

                            b1.Property<TimeOnly?>("StartDate")
                                .HasColumnType("time without time zone");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Thursday", "Domain.Entities.WorkSchedule.Thursday#WorkingHours", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<TimeOnly?>("EndDate")
                                .HasColumnType("time without time zone");

                            b1.Property<TimeOnly?>("StartDate")
                                .HasColumnType("time without time zone");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Tuesday", "Domain.Entities.WorkSchedule.Tuesday#WorkingHours", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<TimeOnly?>("EndDate")
                                .HasColumnType("time without time zone");

                            b1.Property<TimeOnly?>("StartDate")
                                .HasColumnType("time without time zone");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Wednesday", "Domain.Entities.WorkSchedule.Wednesday#WorkingHours", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<TimeOnly?>("EndDate")
                                .HasColumnType("time without time zone");

                            b1.Property<TimeOnly?>("StartDate")
                                .HasColumnType("time without time zone");
                        });

                    b.HasKey("Id");

                    b.ToTable("WorkSchedules", "Telemetry");
                });

            modelBuilder.Entity("DoctorPatient", b =>
                {
                    b.HasOne("Domain.Entities.Patient", null)
                        .WithMany()
                        .HasForeignKey("PatientsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Doctor", null)
                        .WithMany()
                        .HasForeignKey("doctorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Appointment", b =>
                {
                    b.HasOne("Domain.Entities.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Domain.Entities.CalendarBlock", b =>
                {
                    b.HasOne("Domain.Entities.Doctor", "Doctor")
                        .WithOne()
                        .HasForeignKey("Domain.Entities.CalendarBlock", "DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Domain.ValueObjects.Period", "period", b1 =>
                        {
                            b1.Property<Guid>("CalendarBlockId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("EndDate")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTime>("StartDate")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("CalendarBlockId");

                            b1.ToTable("CalendarBlocks", "Telemetry");

                            b1.WithOwner()
                                .HasForeignKey("CalendarBlockId");
                        });

                    b.Navigation("Doctor");

                    b.Navigation("period")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Doctor", b =>
                {
                    b.HasOne("Clinic", "Clinic")
                        .WithMany("Doctors")
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.DoctorInfo", "DoctorInfo")
                        .WithOne()
                        .HasForeignKey("Domain.Entities.Doctor", "DoctorInfoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Clinic");

                    b.Navigation("DoctorInfo");
                });

            modelBuilder.Entity("Domain.Entities.Patient", b =>
                {
                    b.HasOne("Domain.Entities.MedicalRecord", "MedicalRecord")
                        .WithOne()
                        .HasForeignKey("Domain.Entities.Patient", "MedicalRecordId");

                    b.Navigation("MedicalRecord");
                });

            modelBuilder.Entity("Domain.Entities.WorkSchedule", b =>
                {
                    b.HasOne("Domain.Entities.Doctor", "Doctor")
                        .WithOne()
                        .HasForeignKey("Domain.Entities.WorkSchedule", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("Clinic", b =>
                {
                    b.Navigation("Doctors");
                });

            modelBuilder.Entity("Domain.Entities.Doctor", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("Domain.Entities.Patient", b =>
                {
                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
