// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(TelemetryContext))]
    [Migration("20251101200208_Seeds")]
    partial class Seeds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Telemetry")
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Clinic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Clinics", "Telemetry");

                    b.HasData(
                        new
                        {
                            Id = new Guid("14444444-4444-4444-4444-444444444444"),
                            Address = "123 Main Street",
                            City = "New York"
                        },
                        new
                        {
                            Id = new Guid("24444444-4444-4444-4444-444444444444"),
                            Address = "456 Oak Avenue",
                            City = "Los Angeles"
                        },
                        new
                        {
                            Id = new Guid("34444444-4444-4444-4444-444444444444"),
                            Address = "789 Pine Street",
                            City = "Chicago"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Address = "321 Elm Street",
                            City = "Houston"
                        },
                        new
                        {
                            Id = new Guid("54444444-4444-4444-4444-444444444444"),
                            Address = "654 Beach Boulevard",
                            City = "Miami"
                        });
                });

            modelBuilder.Entity("DoctorPatient", b =>
                {
                    b.Property<Guid>("PatientsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("doctorsId")
                        .HasColumnType("uuid");

                    b.HasKey("PatientsId", "doctorsId");

                    b.HasIndex("doctorsId");

                    b.ToTable("DoctorPatient", "Telemetry");
                });

            modelBuilder.Entity("Domain.Entities.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Appointments", "Telemetry");
                });

            modelBuilder.Entity("Domain.Entities.Doctor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<Guid>("ClinicId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DoctorInfoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("WorkScheduleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId");

                    b.HasIndex("DoctorInfoId");

                    b.HasIndex("WorkScheduleId");

                    b.ToTable("Doctors", "Telemetry");

                    b.HasData(
                        new
                        {
                            Id = new Guid("530fde18-4608-46c5-86f9-0b3b6a796477"),
                            Capacity = 17,
                            ClinicId = new Guid("34444444-4444-4444-4444-444444444444"),
                            Specialty = "Orthopedics"
                        },
                        new
                        {
                            Id = new Guid("23b44eb4-fd3d-412e-9173-16c9637b54de"),
                            Capacity = 6,
                            ClinicId = new Guid("34444444-4444-4444-4444-444444444444"),
                            Specialty = "Neurology"
                        },
                        new
                        {
                            Id = new Guid("97d04abc-f378-4f3a-be32-cbc6c263e651"),
                            Capacity = 37,
                            ClinicId = new Guid("34444444-4444-4444-4444-444444444444"),
                            Specialty = "Pediatrics"
                        },
                        new
                        {
                            Id = new Guid("980e468b-16cd-40e4-af35-8a6eb3187814"),
                            Capacity = 27,
                            ClinicId = new Guid("24444444-4444-4444-4444-444444444444"),
                            Specialty = "Psychiatry"
                        },
                        new
                        {
                            Id = new Guid("4b435321-57aa-4824-b84d-b9c0b6d48026"),
                            Capacity = 27,
                            ClinicId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Specialty = "Ophthalmology"
                        },
                        new
                        {
                            Id = new Guid("faca1a7f-7ef7-42ac-bb64-d04675705cc3"),
                            Capacity = 39,
                            ClinicId = new Guid("24444444-4444-4444-4444-444444444444"),
                            Specialty = "Psychiatry"
                        },
                        new
                        {
                            Id = new Guid("8b99fbe5-3c4e-4f62-8d80-75ef7ae24e3c"),
                            Capacity = 38,
                            ClinicId = new Guid("24444444-4444-4444-4444-444444444444"),
                            Specialty = "Radiology"
                        },
                        new
                        {
                            Id = new Guid("0c20650f-2292-49be-a8ca-472840796d01"),
                            Capacity = 16,
                            ClinicId = new Guid("34444444-4444-4444-4444-444444444444"),
                            Specialty = "Ophthalmology"
                        },
                        new
                        {
                            Id = new Guid("c34404bb-0b48-46a7-8548-524cc7832dc8"),
                            Capacity = 7,
                            ClinicId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Specialty = "Psychiatry"
                        },
                        new
                        {
                            Id = new Guid("96888a6c-33e7-4d3f-8358-0e920aa0a9ff"),
                            Capacity = 20,
                            ClinicId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Specialty = "Oncology"
                        },
                        new
                        {
                            Id = new Guid("5e455427-77cb-4487-ab64-65c41fd7b323"),
                            Capacity = 8,
                            ClinicId = new Guid("34444444-4444-4444-4444-444444444444"),
                            Specialty = "Pediatrics"
                        },
                        new
                        {
                            Id = new Guid("f5a65ca9-4f63-4f7e-8fdb-a3adcb8deaee"),
                            Capacity = 21,
                            ClinicId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Specialty = "Ophthalmology"
                        },
                        new
                        {
                            Id = new Guid("7bd13973-1f8b-47f4-854e-5cf7fe3b9e35"),
                            Capacity = 30,
                            ClinicId = new Guid("34444444-4444-4444-4444-444444444444"),
                            Specialty = "Cardiology"
                        },
                        new
                        {
                            Id = new Guid("dacf14e9-77da-4790-a8ac-939a050cd05d"),
                            Capacity = 16,
                            ClinicId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Specialty = "Cardiology"
                        },
                        new
                        {
                            Id = new Guid("3fae1883-20e2-4104-8b24-50c7a33a887c"),
                            Capacity = 14,
                            ClinicId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Specialty = "Orthopedics"
                        },
                        new
                        {
                            Id = new Guid("cd5e3176-456d-459a-b794-83147d10e4d8"),
                            Capacity = 5,
                            ClinicId = new Guid("24444444-4444-4444-4444-444444444444"),
                            Specialty = "Pediatrics"
                        },
                        new
                        {
                            Id = new Guid("70e6d464-0e41-456c-afe7-f641b5515571"),
                            Capacity = 9,
                            ClinicId = new Guid("34444444-4444-4444-4444-444444444444"),
                            Specialty = "Orthopedics"
                        },
                        new
                        {
                            Id = new Guid("cd31ed37-c71d-422a-935e-3382a949153d"),
                            Capacity = 38,
                            ClinicId = new Guid("24444444-4444-4444-4444-444444444444"),
                            Specialty = "Surgery"
                        },
                        new
                        {
                            Id = new Guid("8a6e1429-d9bc-4187-b800-109beab8b73e"),
                            Capacity = 9,
                            ClinicId = new Guid("24444444-4444-4444-4444-444444444444"),
                            Specialty = "Surgery"
                        },
                        new
                        {
                            Id = new Guid("b32bcc97-6449-4b79-a47c-d8de2f5873e5"),
                            Capacity = 6,
                            ClinicId = new Guid("34444444-4444-4444-4444-444444444444"),
                            Specialty = "Ophthalmology"
                        });
                });

            modelBuilder.Entity("Domain.Entities.DomainEntities.MedicalRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("MedicalRecords", "Telemetry");
                });

            modelBuilder.Entity("Domain.Entities.DomainEntities.WorkSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("WorkSchedules", "Telemetry");
                });

            modelBuilder.Entity("Domain.Entities.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("MedicalRecordId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MedicalRecordId");

                    b.ToTable("Patients", "Telemetry");
                });

            modelBuilder.Entity("Domain.Entities.SupportEntities.DoctorInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Awards")
                        .HasColumnType("text");

                    b.Property<string>("Education")
                        .HasColumnType("text");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Publications")
                        .HasColumnType("text");

                    b.Property<string>("Qualifications")
                        .HasColumnType("text");

                    b.Property<string>("ShortBio")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DoctorInfos", "Telemetry");
                });

            modelBuilder.Entity("DoctorPatient", b =>
                {
                    b.HasOne("Domain.Entities.Patient", null)
                        .WithMany()
                        .HasForeignKey("PatientsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Doctor", null)
                        .WithMany()
                        .HasForeignKey("doctorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Appointment", b =>
                {
                    b.HasOne("Domain.Entities.Doctor", "doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Patient", "patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Domain.ValueObjects.Period", "EventPeriod", b1 =>
                        {
                            b1.Property<Guid>("AppointmentId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("EndDate")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTime>("StartDate")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("AppointmentId");

                            b1.ToTable("Appointments", "Telemetry");

                            b1.WithOwner()
                                .HasForeignKey("AppointmentId");
                        });

                    b.Navigation("EventPeriod")
                        .IsRequired();

                    b.Navigation("doctor");

                    b.Navigation("patient");
                });

            modelBuilder.Entity("Domain.Entities.Doctor", b =>
                {
                    b.HasOne("Clinic", "Clinic")
                        .WithMany()
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.SupportEntities.DoctorInfo", "DoctorInfo")
                        .WithMany()
                        .HasForeignKey("DoctorInfoId");

                    b.HasOne("Domain.Entities.DomainEntities.WorkSchedule", "WorkSchedule")
                        .WithMany()
                        .HasForeignKey("WorkScheduleId");

                    b.Navigation("Clinic");

                    b.Navigation("DoctorInfo");

                    b.Navigation("WorkSchedule");
                });

            modelBuilder.Entity("Domain.Entities.DomainEntities.WorkSchedule", b =>
                {
                    b.OwnsOne("Domain.ValueObjects.Period", "Friday", b1 =>
                        {
                            b1.Property<Guid>("WorkScheduleId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("EndDate")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTime>("StartDate")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("WorkScheduleId");

                            b1.ToTable("WorkSchedules", "Telemetry");

                            b1.WithOwner()
                                .HasForeignKey("WorkScheduleId");
                        });

                    b.OwnsOne("Domain.ValueObjects.Period", "Monday", b1 =>
                        {
                            b1.Property<Guid>("WorkScheduleId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("EndDate")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTime>("StartDate")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("WorkScheduleId");

                            b1.ToTable("WorkSchedules", "Telemetry");

                            b1.WithOwner()
                                .HasForeignKey("WorkScheduleId");
                        });

                    b.OwnsOne("Domain.ValueObjects.Period", "Saturday", b1 =>
                        {
                            b1.Property<Guid>("WorkScheduleId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("EndDate")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTime>("StartDate")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("WorkScheduleId");

                            b1.ToTable("WorkSchedules", "Telemetry");

                            b1.WithOwner()
                                .HasForeignKey("WorkScheduleId");
                        });

                    b.OwnsOne("Domain.ValueObjects.Period", "Sunday", b1 =>
                        {
                            b1.Property<Guid>("WorkScheduleId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("EndDate")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTime>("StartDate")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("WorkScheduleId");

                            b1.ToTable("WorkSchedules", "Telemetry");

                            b1.WithOwner()
                                .HasForeignKey("WorkScheduleId");
                        });

                    b.OwnsOne("Domain.ValueObjects.Period", "Thursday", b1 =>
                        {
                            b1.Property<Guid>("WorkScheduleId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("EndDate")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTime>("StartDate")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("WorkScheduleId");

                            b1.ToTable("WorkSchedules", "Telemetry");

                            b1.WithOwner()
                                .HasForeignKey("WorkScheduleId");
                        });

                    b.OwnsOne("Domain.ValueObjects.Period", "Tuesday", b1 =>
                        {
                            b1.Property<Guid>("WorkScheduleId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("EndDate")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTime>("StartDate")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("WorkScheduleId");

                            b1.ToTable("WorkSchedules", "Telemetry");

                            b1.WithOwner()
                                .HasForeignKey("WorkScheduleId");
                        });

                    b.OwnsOne("Domain.ValueObjects.Period", "Wednesday", b1 =>
                        {
                            b1.Property<Guid>("WorkScheduleId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("EndDate")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTime>("StartDate")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("WorkScheduleId");

                            b1.ToTable("WorkSchedules", "Telemetry");

                            b1.WithOwner()
                                .HasForeignKey("WorkScheduleId");
                        });

                    b.Navigation("Friday");

                    b.Navigation("Monday");

                    b.Navigation("Saturday");

                    b.Navigation("Sunday");

                    b.Navigation("Thursday");

                    b.Navigation("Tuesday");

                    b.Navigation("Wednesday");
                });

            modelBuilder.Entity("Domain.Entities.Patient", b =>
                {
                    b.HasOne("Domain.Entities.DomainEntities.MedicalRecord", "MedicalRecord")
                        .WithMany()
                        .HasForeignKey("MedicalRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MedicalRecord");
                });

            modelBuilder.Entity("Domain.Entities.Doctor", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("Domain.Entities.Patient", b =>
                {
                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
