// <auto-generated />
using System;
using System.Collections.Generic;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(TelemetryContext))]
    [Migration("20251103191155_patientCOnfiguration")]
    partial class patientCOnfiguration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Telemetry")
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Clinic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Clinics", "Telemetry");

                    b.HasData(
                        new
                        {
                            Id = new Guid("14444444-4444-4444-4444-444444444444"),
                            Address = "123 Main Street",
                            City = "New York"
                        },
                        new
                        {
                            Id = new Guid("24444444-4444-4444-4444-444444444444"),
                            Address = "456 Oak Avenue",
                            City = "Los Angeles"
                        },
                        new
                        {
                            Id = new Guid("34444444-4444-4444-4444-444444444444"),
                            Address = "789 Pine Street",
                            City = "Chicago"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Address = "321 Elm Street",
                            City = "Houston"
                        },
                        new
                        {
                            Id = new Guid("54444444-4444-4444-4444-444444444444"),
                            Address = "654 Beach Boulevard",
                            City = "Miami"
                        });
                });

            modelBuilder.Entity("DoctorPatient", b =>
                {
                    b.Property<Guid>("PatientsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("doctorsId")
                        .HasColumnType("uuid");

                    b.HasKey("PatientsId", "doctorsId");

                    b.HasIndex("doctorsId");

                    b.ToTable("DoctorPatient", "Telemetry");
                });

            modelBuilder.Entity("Domain.Entities.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Appointments", "Telemetry");
                });

            modelBuilder.Entity("Domain.Entities.Doctor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<Guid>("ClinicId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DoctorInfoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId");

                    b.HasIndex("DoctorInfoId")
                        .IsUnique();

                    b.ToTable("Doctors", "Telemetry");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2c9de460-1ee7-47ab-a2b3-111c7ca98eb9"),
                            Capacity = 6,
                            ClinicId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Specialty = "Pediatrics"
                        },
                        new
                        {
                            Id = new Guid("962d1ac1-cd78-43d0-8488-e2524b5e95b3"),
                            Capacity = 8,
                            ClinicId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Specialty = "Radiology"
                        },
                        new
                        {
                            Id = new Guid("14ee900c-6acf-4d0b-aba7-d98d653298e2"),
                            Capacity = 28,
                            ClinicId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Specialty = "Orthopedics"
                        },
                        new
                        {
                            Id = new Guid("96ee3955-d26d-47c1-8928-7d6665471476"),
                            Capacity = 8,
                            ClinicId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Specialty = "Dermatology"
                        },
                        new
                        {
                            Id = new Guid("59d9131a-fe41-4d59-8088-eff820669fa8"),
                            Capacity = 26,
                            ClinicId = new Guid("24444444-4444-4444-4444-444444444444"),
                            Specialty = "Pediatrics"
                        },
                        new
                        {
                            Id = new Guid("49297f67-a9c0-4930-be77-2eab416f9801"),
                            Capacity = 31,
                            ClinicId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Specialty = "Radiology"
                        },
                        new
                        {
                            Id = new Guid("f808d8aa-29aa-40f6-9daa-ee72a2a99f33"),
                            Capacity = 17,
                            ClinicId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Specialty = "Oncology"
                        },
                        new
                        {
                            Id = new Guid("ece7fc37-e147-4db8-a2e5-f1efc91b5865"),
                            Capacity = 22,
                            ClinicId = new Guid("24444444-4444-4444-4444-444444444444"),
                            Specialty = "Surgery"
                        },
                        new
                        {
                            Id = new Guid("93916634-e8c1-4213-9723-e467219c7526"),
                            Capacity = 23,
                            ClinicId = new Guid("24444444-4444-4444-4444-444444444444"),
                            Specialty = "Orthopedics"
                        },
                        new
                        {
                            Id = new Guid("8ae061d2-900f-40c2-aa39-6f5aa551b8f6"),
                            Capacity = 10,
                            ClinicId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Specialty = "Pediatrics"
                        },
                        new
                        {
                            Id = new Guid("6db0b6ea-a19a-4afa-a6d7-d0e3254eb4d3"),
                            Capacity = 6,
                            ClinicId = new Guid("24444444-4444-4444-4444-444444444444"),
                            Specialty = "Ophthalmology"
                        },
                        new
                        {
                            Id = new Guid("926f1199-f03f-4c37-80e0-107c85cd6dc6"),
                            Capacity = 35,
                            ClinicId = new Guid("24444444-4444-4444-4444-444444444444"),
                            Specialty = "Oncology"
                        },
                        new
                        {
                            Id = new Guid("b34aea93-1eab-40d3-9720-3557dce1bb00"),
                            Capacity = 6,
                            ClinicId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Specialty = "Oncology"
                        },
                        new
                        {
                            Id = new Guid("3de53f89-d105-4e92-88fc-b74796d87d69"),
                            Capacity = 32,
                            ClinicId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Specialty = "Dermatology"
                        },
                        new
                        {
                            Id = new Guid("6cd46b07-66bf-40c2-bc16-9e304850e0f0"),
                            Capacity = 9,
                            ClinicId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Specialty = "Pediatrics"
                        },
                        new
                        {
                            Id = new Guid("ba9a4f2b-b565-40fa-aa6c-0dce757fe792"),
                            Capacity = 33,
                            ClinicId = new Guid("34444444-4444-4444-4444-444444444444"),
                            Specialty = "Radiology"
                        },
                        new
                        {
                            Id = new Guid("b41d12cb-12d9-4945-9dd4-cc01e4787c86"),
                            Capacity = 39,
                            ClinicId = new Guid("24444444-4444-4444-4444-444444444444"),
                            Specialty = "Ophthalmology"
                        },
                        new
                        {
                            Id = new Guid("6c213066-a237-42a5-950d-40a3b1df63c4"),
                            Capacity = 21,
                            ClinicId = new Guid("24444444-4444-4444-4444-444444444444"),
                            Specialty = "Ophthalmology"
                        },
                        new
                        {
                            Id = new Guid("42910855-db56-4dc3-b51e-008a1b6ae996"),
                            Capacity = 36,
                            ClinicId = new Guid("34444444-4444-4444-4444-444444444444"),
                            Specialty = "Oncology"
                        },
                        new
                        {
                            Id = new Guid("c41c740f-b8a3-40ee-802d-fc43825b79ac"),
                            Capacity = 12,
                            ClinicId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Specialty = "Radiology"
                        });
                });

            modelBuilder.Entity("Domain.Entities.DomainEntities.CalendarBlock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BlockReason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsBusy")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId")
                        .IsUnique();

                    b.ToTable("CalendarBlocks", "Telemetry");
                });

            modelBuilder.Entity("Domain.Entities.DomainEntities.MedicalRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("MedicalRecords", "Telemetry");
                });

            modelBuilder.Entity("Domain.Entities.DomainEntities.WorkSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.ComplexProperty<Dictionary<string, object>>("Friday", "Domain.Entities.DomainEntities.WorkSchedule.Friday#WorkingHours", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<TimeOnly?>("EndDate")
                                .HasColumnType("time without time zone");

                            b1.Property<TimeOnly?>("StartDate")
                                .HasColumnType("time without time zone");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Monday", "Domain.Entities.DomainEntities.WorkSchedule.Monday#WorkingHours", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<TimeOnly?>("EndDate")
                                .HasColumnType("time without time zone");

                            b1.Property<TimeOnly?>("StartDate")
                                .HasColumnType("time without time zone");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Saturday", "Domain.Entities.DomainEntities.WorkSchedule.Saturday#WorkingHours", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<TimeOnly?>("EndDate")
                                .HasColumnType("time without time zone");

                            b1.Property<TimeOnly?>("StartDate")
                                .HasColumnType("time without time zone");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Sunday", "Domain.Entities.DomainEntities.WorkSchedule.Sunday#WorkingHours", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<TimeOnly?>("EndDate")
                                .HasColumnType("time without time zone");

                            b1.Property<TimeOnly?>("StartDate")
                                .HasColumnType("time without time zone");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Thursday", "Domain.Entities.DomainEntities.WorkSchedule.Thursday#WorkingHours", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<TimeOnly?>("EndDate")
                                .HasColumnType("time without time zone");

                            b1.Property<TimeOnly?>("StartDate")
                                .HasColumnType("time without time zone");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Tuesday", "Domain.Entities.DomainEntities.WorkSchedule.Tuesday#WorkingHours", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<TimeOnly?>("EndDate")
                                .HasColumnType("time without time zone");

                            b1.Property<TimeOnly?>("StartDate")
                                .HasColumnType("time without time zone");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Wednesday", "Domain.Entities.DomainEntities.WorkSchedule.Wednesday#WorkingHours", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<TimeOnly?>("EndDate")
                                .HasColumnType("time without time zone");

                            b1.Property<TimeOnly?>("StartDate")
                                .HasColumnType("time without time zone");
                        });

                    b.HasKey("Id");

                    b.ToTable("WorkSchedules", "Telemetry");
                });

            modelBuilder.Entity("Domain.Entities.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("MedicalRecordId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MedicalRecordId")
                        .IsUnique();

                    b.ToTable("Patients", "Telemetry");
                });

            modelBuilder.Entity("Domain.Entities.SupportEntities.DoctorInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Awards")
                        .HasColumnType("text");

                    b.Property<string>("Education")
                        .HasColumnType("text");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Publications")
                        .HasColumnType("text");

                    b.Property<string>("Qualifications")
                        .HasColumnType("text");

                    b.Property<string>("ShortBio")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DoctorInfos", "Telemetry");
                });

            modelBuilder.Entity("DoctorPatient", b =>
                {
                    b.HasOne("Domain.Entities.Patient", null)
                        .WithMany()
                        .HasForeignKey("PatientsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Doctor", null)
                        .WithMany()
                        .HasForeignKey("doctorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Appointment", b =>
                {
                    b.HasOne("Domain.Entities.Doctor", "doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Patient", "patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Domain.ValueObjects.Period", "EventPeriod", b1 =>
                        {
                            b1.Property<Guid>("AppointmentId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("EndDate")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTime>("StartDate")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("AppointmentId");

                            b1.ToTable("Appointments", "Telemetry");

                            b1.WithOwner()
                                .HasForeignKey("AppointmentId");
                        });

                    b.Navigation("EventPeriod")
                        .IsRequired();

                    b.Navigation("doctor");

                    b.Navigation("patient");
                });

            modelBuilder.Entity("Domain.Entities.Doctor", b =>
                {
                    b.HasOne("Clinic", "Clinic")
                        .WithMany()
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.SupportEntities.DoctorInfo", "DoctorInfo")
                        .WithOne()
                        .HasForeignKey("Domain.Entities.Doctor", "DoctorInfoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Clinic");

                    b.Navigation("DoctorInfo");
                });

            modelBuilder.Entity("Domain.Entities.DomainEntities.CalendarBlock", b =>
                {
                    b.HasOne("Domain.Entities.Doctor", "Doctor")
                        .WithOne()
                        .HasForeignKey("Domain.Entities.DomainEntities.CalendarBlock", "DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Domain.ValueObjects.Period", "period", b1 =>
                        {
                            b1.Property<Guid>("CalendarBlockId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("EndDate")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTime>("StartDate")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("CalendarBlockId");

                            b1.ToTable("CalendarBlocks", "Telemetry");

                            b1.WithOwner()
                                .HasForeignKey("CalendarBlockId");
                        });

                    b.Navigation("Doctor");

                    b.Navigation("period")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.DomainEntities.WorkSchedule", b =>
                {
                    b.HasOne("Domain.Entities.Doctor", "Doctor")
                        .WithOne()
                        .HasForeignKey("Domain.Entities.DomainEntities.WorkSchedule", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("Domain.Entities.Patient", b =>
                {
                    b.HasOne("Domain.Entities.DomainEntities.MedicalRecord", "MedicalRecord")
                        .WithOne()
                        .HasForeignKey("Domain.Entities.Patient", "MedicalRecordId");

                    b.Navigation("MedicalRecord");
                });

            modelBuilder.Entity("Domain.Entities.Doctor", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("Domain.Entities.Patient", b =>
                {
                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
