// <auto-generated />
using System;
using System.Collections.Generic;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(TelemetryContext))]
    [Migration("20260105001814_CalendarBlockConfigurationUpdated")]
    partial class CalendarBlockConfigurationUpdated
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Telemetry")
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Clinic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Clinics", "Telemetry");

                    b.HasData(
                        new
                        {
                            Id = new Guid("14444444-4444-4444-4444-444444444444"),
                            Address = "123 Main Street",
                            City = "New York"
                        },
                        new
                        {
                            Id = new Guid("24444444-4444-4444-4444-444444444444"),
                            Address = "456 Oak Avenue",
                            City = "Los Angeles"
                        },
                        new
                        {
                            Id = new Guid("34444444-4444-4444-4444-444444444444"),
                            Address = "789 Pine Street",
                            City = "Chicago"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Address = "321 Elm Street",
                            City = "Houston"
                        },
                        new
                        {
                            Id = new Guid("54444444-4444-4444-4444-444444444444"),
                            Address = "654 Beach Boulevard",
                            City = "Miami"
                        });
                });

            modelBuilder.Entity("DoctorPatient", b =>
                {
                    b.Property<Guid>("DoctorsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PatientsId")
                        .HasColumnType("uuid");

                    b.HasKey("DoctorsId", "PatientsId");

                    b.HasIndex("PatientsId");

                    b.ToTable("DoctorPatient", "Telemetry");
                });

            modelBuilder.Entity("Domain.Entities.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.ComplexProperty<Dictionary<string, object>>("EventPeriod", "Domain.Entities.Appointment.EventPeriod#Period", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTime>("EndDate")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTime>("StartDate")
                                .HasColumnType("timestamp with time zone");
                        });

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Appointments", "Telemetry");
                });

            modelBuilder.Entity("Domain.Entities.CalendarBlock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BlockReason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsBusy")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.ToTable("CalendarBlocks", "Telemetry");
                });

            modelBuilder.Entity("Domain.Entities.Doctor", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<Guid>("ClinicId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DoctorInfoId")
                        .HasColumnType("uuid");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId");

                    b.HasIndex("DoctorInfoId")
                        .IsUnique();

                    b.ToTable("Doctors", "Telemetry");
                });

            modelBuilder.Entity("Domain.Entities.DoctorInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Awards")
                        .HasColumnType("text");

                    b.Property<string>("Education")
                        .HasColumnType("text");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Publications")
                        .HasColumnType("text");

                    b.Property<string>("Qualifications")
                        .HasColumnType("text");

                    b.Property<string>("ShortBio")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DoctorInfos", "Telemetry");
                });

            modelBuilder.Entity("Domain.Entities.MedicalRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("MedicalRecords", "Telemetry");
                });

            modelBuilder.Entity("Domain.Entities.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("MedicalRecordId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MedicalRecordId")
                        .IsUnique();

                    b.ToTable("Patients", "Telemetry");
                });

            modelBuilder.Entity("Domain.Entities.WorkSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.ComplexProperty<Dictionary<string, object>>("Friday", "Domain.Entities.WorkSchedule.Friday#WorkingHours", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<TimeOnly?>("EndDate")
                                .HasColumnType("time without time zone");

                            b1.Property<TimeOnly?>("StartDate")
                                .HasColumnType("time without time zone");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Monday", "Domain.Entities.WorkSchedule.Monday#WorkingHours", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<TimeOnly?>("EndDate")
                                .HasColumnType("time without time zone");

                            b1.Property<TimeOnly?>("StartDate")
                                .HasColumnType("time without time zone");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Saturday", "Domain.Entities.WorkSchedule.Saturday#WorkingHours", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<TimeOnly?>("EndDate")
                                .HasColumnType("time without time zone");

                            b1.Property<TimeOnly?>("StartDate")
                                .HasColumnType("time without time zone");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Sunday", "Domain.Entities.WorkSchedule.Sunday#WorkingHours", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<TimeOnly?>("EndDate")
                                .HasColumnType("time without time zone");

                            b1.Property<TimeOnly?>("StartDate")
                                .HasColumnType("time without time zone");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Thursday", "Domain.Entities.WorkSchedule.Thursday#WorkingHours", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<TimeOnly?>("EndDate")
                                .HasColumnType("time without time zone");

                            b1.Property<TimeOnly?>("StartDate")
                                .HasColumnType("time without time zone");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Tuesday", "Domain.Entities.WorkSchedule.Tuesday#WorkingHours", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<TimeOnly?>("EndDate")
                                .HasColumnType("time without time zone");

                            b1.Property<TimeOnly?>("StartDate")
                                .HasColumnType("time without time zone");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Wednesday", "Domain.Entities.WorkSchedule.Wednesday#WorkingHours", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<TimeOnly?>("EndDate")
                                .HasColumnType("time without time zone");

                            b1.Property<TimeOnly?>("StartDate")
                                .HasColumnType("time without time zone");
                        });

                    b.HasKey("Id");

                    b.ToTable("WorkSchedules", "Telemetry");
                });

            modelBuilder.Entity("DoctorPatient", b =>
                {
                    b.HasOne("Domain.Entities.Doctor", null)
                        .WithMany()
                        .HasForeignKey("DoctorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Patient", null)
                        .WithMany()
                        .HasForeignKey("PatientsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Appointment", b =>
                {
                    b.HasOne("Domain.Entities.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Domain.Entities.CalendarBlock", b =>
                {
                    b.HasOne("Domain.Entities.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Domain.ValueObjects.Period", "period", b1 =>
                        {
                            b1.Property<Guid>("CalendarBlockId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("EndDate")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTime>("StartDate")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("CalendarBlockId");

                            b1.ToTable("CalendarBlocks", "Telemetry");

                            b1.WithOwner()
                                .HasForeignKey("CalendarBlockId");
                        });

                    b.Navigation("Doctor");

                    b.Navigation("period")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Doctor", b =>
                {
                    b.HasOne("Clinic", "Clinic")
                        .WithMany("Doctors")
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.DoctorInfo", "DoctorInfo")
                        .WithOne()
                        .HasForeignKey("Domain.Entities.Doctor", "DoctorInfoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Clinic");

                    b.Navigation("DoctorInfo");
                });

            modelBuilder.Entity("Domain.Entities.Patient", b =>
                {
                    b.HasOne("Domain.Entities.MedicalRecord", "MedicalRecord")
                        .WithOne()
                        .HasForeignKey("Domain.Entities.Patient", "MedicalRecordId");

                    b.Navigation("MedicalRecord");
                });

            modelBuilder.Entity("Domain.Entities.WorkSchedule", b =>
                {
                    b.HasOne("Domain.Entities.Doctor", "Doctor")
                        .WithOne()
                        .HasForeignKey("Domain.Entities.WorkSchedule", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("Clinic", b =>
                {
                    b.Navigation("Doctors");
                });

            modelBuilder.Entity("Domain.Entities.Doctor", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("Domain.Entities.Patient", b =>
                {
                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
